# Site settings
title:       Shmuel Rosansky
email:       orbitdesignco@gmail.com
author:      Shmuel Rosansky
description: "Tech musings and random streams of consciousness"
baseurl:     ""
url:         "http://shmuelrosansky.com"

# Google analytics
google_analytics: UA-65249816-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: shmuelr
stackoverflow_id: 1764080
twitter_username:
google_plus_id: 113411818492269662250
linkedin_username: shmuelr
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
